branches:
  only:
    - master

notifications:
  email:
    - gregczajkowski@yahoo.com

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -q; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y automake pkg-config zlib1g-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libzmq3-dev; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm pyzmq libzmq3-dev && brew link --force llvm; fi


# command to install dependencies
install:
  - pip install pyzmq

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"

# command to run tests
script:
  - make pytest

os:
  - linux
  - osx
